### ISSUE TITLE
Plugin not working on Grafana 6.x

### ISSUE THREAD

**Issue by sawo1337** [savantly-net/grafana-heatmap#20]
On Grafana 6.x the plugin installs fine, but when used, displays error "Panel plugin not found: savantly-heatmap-panel"

Seems like the files are in their expected places, but something is not working as expected.

**Comment by sawo1337** [comment]
The issue was related to the Firefox plugin uBlock origin preventing some of the scripts from loading

**Comment by butlerx** [comment]
any reason this plugin would be blocked by ublock origin?
